/*

 BLOKE2.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char bloke2[] =
{
  0x7E,0x7E,0x81,0xFF,0x00,0xFF,0x1C,0xE7,
  0x1C,0xE3,0x00,0xFE,0x1E,0x7E,0x3F,0x3F
};

/* End of BLOKE2.C */
