/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : bgTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgMapWidth 40
#define bgMapHeight 18
#define bgMapBank 0

extern unsigned char bgMap[];

/* End of BGMAP.H */
