/*

 LEVELMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\bryan\develop\gameboyC\resource\levelBall.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelMapWidth 20
#define levelMapHeight 18
#define levelMapBank 0

extern unsigned char levelMap[];

/* End of LEVELMAP.H */
