/*

 LEVEL01MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\gameboyC\04bg\level01Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level01MapWidth 40
#define level01MapHeight 18
#define level01MapBank 0

extern unsigned char level01Map[];

/* End of LEVEL01MAP.H */
