/*

 SPRITEPAC.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char pacMan[] =
{
  0x3C,0x3C,0x7E,0x42,0xFF,0x91,0xFF,0x81,
  0xFF,0x8F,0xFF,0x81,0x7E,0x42,0x3C,0x3C,
  0x3C,0x3C,0x7E,0x42,0xFF,0x91,0xFE,0x86,
  0xF0,0x90,0xF8,0x88,0x7C,0x44,0x38,0x38
};

/* End of SPRITEPAC.C */
